version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-workbench
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
